config:
  send_anonymous_usage_stats: False

sde_dbt_tutorial:
  target: prod
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 15432
      user: dbt
      pass: password1234
      dbname: dbt
      schema: warehouse
    prod:
      type: vertica
      threads: 1
      host: localhost
      port: 5433
      username: dbt
      password: password1234
      database: dbt
      schema: warehouse
